### ISSUE TITLE
SVG rendering issue when svg-tag-mode is installed

### ISSUE THREAD

**Issue by onnyyonn** [rougier/svg-tag-mode#18] opened 2022-01-01 04:06 UTC
I am using Emacs 27.2 on Arch Linux with Doom Emacs configuration. Normally Emacs can render SVG just fine for me, Evaluating `(image-type-available-p 'svg)` returns `t`. But when I install svg-tag-mode, Emacs seems to be unable to render SVG.

Here is an example when svg-tag-mode is on:
![Screenshot_20211231_223758](https://user-images.githubusercontent.com/963267/147843688-dce9cfe3-98b2-4c8f-b731-319effb20f64.png)

For comparison, when svg-tag-mode is off:
![Screenshot_20211231_223721](https://user-images.githubusercontent.com/963267/147843701-9f29cc41-7f6c-4f74-9e6e-a6d17a98cb2f.png)

With svg-tag-mode installed other SVG images, unrelated to the package, are also not rendered.

**Comment by its-a-unixsystem** [comment] 2022-01-01 21:27
Same problem (and output), for me: (Emcas 28.0.90, Org mode version 9.5.1 (release_9.5.1-288-gf0c474)).
The examples from svg-lib work though, including when executing the org-mode code in a scratch buffer, so possibly a problem with some org-mode features (I tried to switch off some stuff, but couldnt find the problem)

**Comment by mkvoya** [comment] 2022-01-02 09:48
An experiment:
1. when I first enable the org-mode, I can insert an svg image to the buffer via `(insert-image (svg-tag-make "HI"))`. Everything works fine;
2. I then enable the svg-tag-mode, the "HI" tag inserted in step 1 becomes a whitespace and when insert the svg image again, a whitespace is inserted.
3. I then disable the svg-tag-mode, still whitespaces.

Another thing is perhaps a little bit off-topic, but shall we use `(font-lock-update)` to replace `(font-lock-flush)` so that the original org-mode styles can be preserved? As you can see in the issue, when svg-tag-mode is on, `* Test` becomes plaintext without any color.

https://github.com/rougier/svg-tag-mode/blob/3b07983614bee0195534e7a8a6dcfab757da4f0b/svg-tag-mode.el#L305-L308

**Comment by rougier** [comment] 2022-01-03 21:55
I modified org mode renderign a bit at line [280](https://github.com/rougier/svg-tag-mode/blob/main/svg-tag-mode.el#L280) but I'm not sure why this would interfere with other SVG display. Could you try to disable it (by evaluating the buffer with the line commended)?

**Comment by rougier** [comment] 2022-01-03 21:56
@mkvoya I thought `(font-lock-flush)` was doing an update but now I'm not so sure. What's the difference between the two fucntions?

**Comment by its-a-unixsystem** [comment] 2022-01-04 07:15
Hi @rougier thanks for helping.

1. I commented out the line with the `advice-add `call
```
>diff .emacs.d/elpa/svg-tag-mode-20211229.920/svg-tag-mode.el .emacs.d/elpa/svg-tag-mode-20211229.920/svg-tag-mode.el.bak
282,283c282,283
< ;;  (advice-add 'org-fontify-meta-lines-and-blocks
< ;;              :around #'svg-tag--org-fontify-meta-lines-and-blocks)
---
>   (advice-add 'org-fontify-meta-lines-and-blocks
>               :around #'svg-tag--org-fontify-meta-lines-and-blocks)

```
2. deleted the `.elc` and `eln-cache` files
3. eval-buffer
5. my config:
```
(require 'svg-lib)
(use-package svg-tag-mode
    :ensure t)
(setq svg-tag-tags
      '((":TODO:" . ((svg-tag-make "TODO")))))
```
6. open an org-file with an tag `:TODO:` (before):
![20220104_08h11m38s_grim](https://user-images.githubusercontent.com/44412644/148022464-988f9c6d-8f17-43af-a7de-3144be0e561f.png)

7. M-x svg-tag-mode

The result still the same:
![20220104_08h12m57s_grim](https://user-images.githubusercontent.com/44412644/148022515-35482a5f-e8bd-4751-bedf-e38035b73aaf.png)

**Comment by mkvoya** [comment] 2022-01-04 11:46
> @mkvoya I thought `(font-lock-flush)` was doing an update but now I'm not so sure. What's the difference between the two fucntions?

Sorry, I am not familiar with the two functions either. And I cannot reproduce my issue now.

@its-a-unixsystem could you please try to use 'font-lock-update' and check whether that can preserve existing org styles? 😀

**Comment by its-a-unixsystem** [comment] 2022-01-04 12:14
replacing `font-lock-flush` with `font-lock-update` gives me an error:
[debug.txt](https://github.com/rougier/svg-tag-mode/files/7807459/debug.txt)
(same with and without `advice-add` commented out)

**Comment by rougier** [comment] 2022-01-04 13:08
@its-a-unixsystem Can you try `(setq svg-tag-tags
      '((":TODO:" . ((lambda (tag) (svg-tag-make "TODO"))))))`

**Comment by its-a-unixsystem** [comment] 2022-01-05 10:56
Woohoo, it renders (with unmodified svg-tag/svg-lib files)
![image](https://user-images.githubusercontent.com/44412644/148206629-0ac1de23-1a5d-4b49-bb8a-95e47dab4ea4.png)

**Comment by rougier** [comment] 2022-01-05 11:42
We also pushed a fix to the svg-lib that should solved the font size issue (not yet on ELPA).

**Comment by mkvoya** [comment] 2022-01-05 14:20
> replacing `font-lock-flush` with `font-lock-update` gives me an error:
> [debug.txt](https://github.com/rougier/svg-tag-mode/files/7807459/debug.txt)
> (same with and without `advice-add` commented out)

It seems that I was wrong. Just ignore me and thanks for your help. :)

**Comment by proudot** [comment] 2022-01-12 13:20
> We also pushed a fix to the svg-lib that should solved the font size issue (not yet on ELPA).

Thanks a lot! Do you know when it will be on elpa ? I want to update it to the last version but I use "use-package" and do not want to mess it up.  No rush, just curious.

**Comment by rougier** [comment] 2022-01-17 16:14
Just pushed svg-lib 0.2.5 on ELPA. It shoudl be online in a few minutes.

**Comment by proudot** [comment] 2022-01-18 10:14
And it works wonderfully! Thanks a ton!

**Comment by its-a-unixsystem** [comment] 2022-01-18 12:03
The original issue is resolved, waiting for https://github.com/rougier/svg-tag-mode/pull/14 and 12, so I guess we can close here

**Closed** 2022-01-18 14:29 UTC
